### ISSUE TITLE
数据库脚本报错

### ISSUE THREAD

**Issue by dev-penghui** [TouShang6015/Hugai-chatgpt#1]
字符串编码千奇百怪的，麻烦检查一下再发吧

**Comment by TouShang6015** [comment]
> 字符串编码千奇百怪的，麻烦检查一下再发吧

感谢提出的问题。统一了字符集编码， [fb4fba6](https://github.com/TouShang6015/Hugai-chatgpt/commit/fb4fba6ebb0cf8519b8b4d901e88f65669c91ca8)
