### ISSUE TITLE
没有私有的bebas-common包

### ISSUE THREAD

**Issue by wordall1101** [TouShang6015/Hugai-chatgpt#3]
<repositories>
        <repository>
            <id>common</id>
            <url>https://toushang6015.github.io/bebas-common/maven-repo/</url>
        </repository>
        <repository>
            <id>common-service</id>
            <url>https://toushang6015.github.io/bebas-common-service/maven-repo/</url>
        </repository>
    </repositories>

**Comment by TouShang6015** [comment]
看看这个解决方法 #2
