### ISSUE TITLE
maven 私有仓库访问不到

### ISSUE THREAD

**Issue by yangbod** [TouShang6015/Hugai-chatgpt#4]
下面3个仓库地址都不能访问到
https://toushang6015.github.io/bebas-common/maven-repo/
https://toushang6015.github.io/bebas-common-service/maven-repo/
https://toushang6015.github.io/v8jisu-payment-api/maven-repo/

**Comment by TouShang6015** [comment]
参考下这个 #2 ，maven的setting.xml文件mirrorOf标签不要配置*号
